### PR TITLE
client: Quicker reconnect on broker failure

### LINKED ISSUE #65: Client behavior on broker restart is suboptimal
Currently, if the broker is restarted (i.e., sent a SIGINT and then started again), the following happens on the client:
* It starts out in STATE_KEEPALIVE, receives the error, switches to STATE_REINIT
* In context_process, this leads to calling context_reinitialize and then context_start_connect. In particular, `standby_only` gets set to true and the state switches to STATE_GET_COOKIE.
* The client sends a cookie request, and receives the response from the server that has come back up in the mean time.
* Upon receiving the reply, the client notices that `standby_only` is set, and does nothing.
* 30 seconds later, the main loop notices that the client has not been connected for 30 seconds, and restarts full broker selection, which eventually selects a sensible broker again.

This is probably not the intended behavior. However, I have a hard time figuring out the intended behavior, because there are two things in the main loop for detecting an error, and two things the other code does in case of error: The main loops checks for STATE_REINIT, and it starts a timer if the state is not STATE_KEEPALIVE. The other code sometimes goes to STATE_GET_COOKIE, sometimes to STATE_REINIT -- but in the latter case, context_process gets called before the main loop notices this state.

My inclination is to: (a) remove the STATE_REINIT check in the main loop; it doesn't work anyway; instead maybe the main connection timer should be lowered so that we get away from a bad broker faster. (b) make it so that when we receive an error in a running tunnel, we stick with this broker (like we do now), but do not set `standby_only` (which is clearly wrong). I think this requires another parameter to context_reinitialize saying whether the new context should be standby-only or not.

### PR DESCRIPTION
**Pull request by RalfJung**
This drops support for brokers that do not reply to a USAGE query. The advantage of that is that we can already tell from the state we are in whether we are in the "first phase" (scanning all brokers to see which ones are available) or the "second phase" (establishing and maintaining a tunnel with the broker).

Based on that, we can drop `standby_only`. We can also make sure that, once we are in the "second phase", if we ever jump to the "first phase" again, the main loop restarts the entire thing. I also decreased some timeouts to minimize the downtime in case a broker is shut down or restarted.

Before this patch, restarting a broker (if all other brokers are running) had a downtime of around 30s (until the main loop realizes that the connection is gone). This is despite the fact that the client got an ERROR, telling it that the broker went away! Stopping a broker (or restarting a broker while another broker is down) even lead to a downtime of 50s, because the client waits for 20s until it realizes that no reply is going to come to its USAGE query. With this patch, in both cases, the downtime is below 10s.

Fixes #65

### CODE REVIEW

**Comment by RalfJung** [comment]
The CI fails, it seems it actually tests that the client still works with old brokers.

Considering that typically, the brokers are much easier to update than the client (AFAIK), is it acceptable to drop this compatibility? Old clients should still work with new brokers, as this only affects the client's state machine.

**Comment by RalfJung** [comment]
I reworked the patches to maintain support with old servers, and rebased on top of current master.

**Comment by RalfJung** [comment]
@kostko Should I rebase again? I can keep doing that, but so far I got no feedback whatsoever on this PR.

**Comment by mitar** [comment]
I am not sure about the content, but please do rebase because this will also test against v0.3.0 which you added and was just merged, no?

**Comment by RalfJung** [comment]
Good point. Done.

**Comment by RalfJung** [comment]
Looking good :)

File: client/l2tp_client.c [hunk 1]
```diff
@@ -1386,6 +1419,10 @@ int main(int argc, char **argv)
     // Make sure all brokers are in sane state.
     for (i = 0; i < broker_cnt; i++) {
       context_reinitialize(brokers[i].ctx);
+      if (brokers[i].broken && brokers[i].broken + 3600 < timer_now()) {
```
Comment (kostko) [inline client/l2tp_client.c]: Should the retry period be made configurable instead of hardcoded to 3600 seconds?

File: client/l2tp_client.c [hunk 2]
```diff
@@ -1449,46 +1484,43 @@ int main(int argc, char **argv)
...
         syslog(LOG_ERR, "Connection to %s lost.", main_context->broker_hostname);
         break;
-      } else if (main_context->state == STATE_KEEPALIVE) {
-        // We successfully established a connection, this broker is fine.
-        brokers[i].broken = 0;
       }
 
       // If the connection is lost, we start the reconnection timer.
-      if (restart_timer && main_context->state != STATE_KEEPALIVE) {
+      // Hitting this code path should not be possible, but lets play safe.
```
Comment (kostko) [inline client/l2tp_client.c]: Can you add an explanation why in the comment?

File: client/l2tp_client.c [hunk 3]
```diff
@@ -115,15 +115,40 @@ enum l2tp_limit_type {
   LIMIT_TYPE_BANDWIDTH_DOWN = 0x01
 };
 
+/* The state machine looks as follows:
```
Comment (kostko) [inline client/l2tp_client.c]: :+1:

File: client/l2tp_client.c (hunk 1 above)
Comment (RalfJung) [reply client/l2tp_client.c]: This is not the only timeout -- there's also the 20s (I think) for the initial availability check, and the 10s for restarting the entire thing.

I considered making them all macros, but did not want the PR to get bigger than necessary. Making them CLI arguments is of course also an option, but is that really useful?

File: client/l2tp_client.c (hunk 2 above)
Comment (RalfJung) [reply client/l2tp_client.c]: Done.

**Comment by RalfJung** [comment]
Any chance of getting this through this week? I'd prefer not to do the firmware update over Christmas. :D
